"""Application services shared by command-line and interactive frontends."""

from .acquisition_queue import (
    QueueItem,
    QueueJob,
    QueueReferenceError,
    QueueSnapshot,
    QueueStatus,
    get_queue_snapshot,
    resolve_queue_reference,
)
from .catalogue import (
    CatalogueFilterMetadata,
    CatalogueFilterOption,
    CataloguePage,
    CatalogueSearchResult,
    LyricAvailability,
    SongDetails,
    get_catalogue_filters,
    get_song_details,
    get_song_details_by_id,
    search_catalogue,
    search_catalogue_page,
)
from .library_status import LibraryStatus, get_library_status
from .library_sync import (
    LibrarySyncDependencies,
    LibrarySyncOptions,
    LibrarySyncPlan,
    LibrarySyncResult,
    MatchOutcome,
    SyncEvent,
    SyncEventKind,
    SyncLyricType,
    TrackSyncPlan,
    TrackSyncResult,
    execute_library_sync,
    plan_library_sync,
)

__all__ = [
    "CatalogueSearchResult",
    "CatalogueFilterMetadata",
    "CatalogueFilterOption",
    "CataloguePage",
    "LibraryStatus",
    "LibrarySyncDependencies",
    "LibrarySyncOptions",
    "LibrarySyncPlan",
    "LibrarySyncResult",
    "LyricAvailability",
    "MatchOutcome",
    "QueueItem",
    "QueueJob",
    "QueueReferenceError",
    "QueueSnapshot",
    "QueueStatus",
    "SongDetails",
    "SyncEvent",
    "SyncEventKind",
    "SyncLyricType",
    "TrackSyncPlan",
    "TrackSyncResult",
    "execute_library_sync",
    "get_catalogue_filters",
    "get_queue_snapshot",
    "get_library_status",
    "get_song_details",
    "get_song_details_by_id",
    "plan_library_sync",
    "search_catalogue",
    "search_catalogue_page",
    "resolve_queue_reference",
]
